[build]
builder = "railpack"

[deploy]
startCommand = "python main.py"

# These variables tell the builder to install the necessary Chrome packages
[variables]
RAILPACK_PACKAGES = "google-chrome,chromedriver"
RAILPACK_DEPLOY_APT_PACKAGES = "libnss3,libatk1.0-0,libatk-bridge2.0-0,libcups2,libdrm2,libxcomposite1,libxdamage1,libxrandr2,libgbm1,libasound2,pango1.0-0,libcairo2"
